version: "3.8"

services:
  mysql:
    image: mysql:5.7.32
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - /data/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 5000:80
    depends_on:
      - mysql